### ISSUE TITLE
Question about bouncer in docker compose

### ISSUE THREAD

**Issue by ipod86** [crowdsecurity/example-docker-compose#24]
I read this line in docker compose. Where is the bouncer added?

https://github.com/crowdsecurity/example-docker-compose/blob/574db5669fee8a49280f5bde7489631dc48c11c1/basic/docker-compose.yml#L32

Can I create this docker compose as it is in portainer as a stack and then have an nginx reverse proxy protected by crowdsec?

Please excuse my bad English

**Comment by LaurenceJJones** [comment]
There is a mistake on this compose, there should be a configuration to expose the port locally for example

```yaml
  crowdsec:
    image: crowdsecurity/crowdsec
    restart: always
    environment:
      #this is the list of collections we want to install
      #https://hub.crowdsec.net/author/crowdsecurity/collections/nginx
      COLLECTIONS: "crowdsecurity/nginx"
      GID: "${GID-1000}"
    depends_on:
      - 'reverse-proxy'
    ports:
      - '127.0.0.1:8080:8080'
    volumes:
      - ./crowdsec/acquis.yaml:/etc/crowdsec/acquis.yaml
      - logs:/var/log/nginx
      - crowdsec-db:/var/lib/crowdsec/data/
      - crowdsec-config:/etc/crowdsec/
    networks:
      crowdsec_test:
        ipv4_address: 172.20.0.4
```

This will allow the firewall bouncer to connect via the local port of `8080`
