### ISSUE TITLE
Appsec installation help

### ISSUE THREAD

**Issue by inthreedee** [crowdsecurity/example-docker-compose#30]
I am attempting to configure appsec for my crowdsec install on nginx proxy manager. Manual tests sent with curl from my NPM container to the crowdsec container confirm appsec is working, but requests to the web apps that are protected by crowdsec don't seem to be caught by appsec. For example, accessing my http://{ip-address}/.env does not trigger appsec and the request is passed through to NPM.

I'm sure it's just a configuration problem on my end, but I could use some help sorting out what I've done wrong.

Here's what I have so far:
- Using the info in this repo (https://github.com/crowdsecurity/example-docker-compose/tree/main/npm) and the LePresidente fork of NPM, I have crowdsec running. It's connected to the web console and is parsing logs and triggering alerts. So far so good.
- Following the instructions in the crowdsec docs (https://docs.crowdsec.net/docs/next/appsec/quickstart/nginxopenresty), I have enabled appsec. I'm able to manually test that appsec is working by launching a shell within my NPM container and issuing the curl command shown in the docs to the crowdsec container. It responds with a 403 forbidden as it should. All good here.
- I finished the configuration in my docker-compose file and restarted the containers, but attempting to access a .env file from my ip address or the urls of my hosted web apps do not seem to trigger appsec as expected, so it doesn't seem like http requests are being sent to the appsec component. Instead, I see either NPM's 404 page, or a 404 from the web app behind NPM that is being accessed.

This is my docker-compose file.
A note about the ports below in case it matters: I'm using rootless docker with the pasta network driver and iptables rules to forward privileged->unprivileged ports (pasta can't be bound to privileged ports). This allows the source IPs from web traffic to propagate into my logs for manual inspection when necessary (rootless docker hides these with a default configuration).
```yaml
services:
  app:
    image: 'lepresidente/nginxproxymanager:latest'
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '8080:80' # Public HTTP Port
      - '4443:443' # Public HTTPS Port
      - '8181:81' # Admin Web Port
    environment:
      PUID: 1000
      GUID: 1000

      CROWDSEC_OPENRESTY_BOUNCER: |
        ENABLED=true
        API_URL=http://crowdsec:8080
        API_KEY=${CROWDSEC_BOUNCER_APIKEY}
        APPSEC_URL=http://crowdsec:7422

    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    security_opt:
      - no-new-privileges=true

  crowdsec:
    image: 'docker.io/crowdsecurity/crowdsec:latest'
    restart: unless-stopped
    container_name: crowdsec
    environment:
      - COLLECTIONS=crowdsecurity/nginx-proxy-manager
    volumes:
      - ./crowdsec/data/:/var/lib/crowdsec/data/
      - ./crowdsec/config/:/etc/crowdsec/
      - ./data/logs/:/var/log/npm:ro
    security_opt:
      - no-new-privileges=true

  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - "/run/user/1000/docker.sock:/var/run/docker.sock"
    command: --cleanup

networks:
  default:
    name: npm_proxy
    external: true
```

This is my acquis.yaml:
```yaml
filenames:
  - /var/log/npm/*.log
labels:
  type: nginx-proxy-manager
---
appsec_config: crowdsecurity/appsec-default
listen_addr: 0.0.0.0:7422
name: appsec
source: appsec
labels:
  type: appsec
```
